permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Pouchly"
  description: |
    Pouchly is a family budgeting app that helps you money and plan for the future.
  font_url: "https://fonts.googleapis.com/css?family=Muli:400,700&display=swap"
  rationales:
    typefaces.primary: |
      Muli is to be used in content throughout the website, button text, links or call to actions, and navigation. It will mostly be used in a bold and normal font weight so to be easily readable and clear on a website. It is a rounded easy to read font that had a family-friendly feel.
    colors.primary: |
      This is the main colour of our logo.
    colors.secondary: |
      This colour is used for icons to grab the eye.
    colors.secondary.pink: |
      This colour is for Hover state on buttons, and progress bars.
    colors.accent: |
      This colour will signify paid bills.
    colors.accent.secondary: |
      This is the background colour.
    colors.accent.tertiary: |
      This is text colour when not black.
    colors.accent.grey: |
      This is light version of accent-tertiary.
  layouts:
    default: |
      The default layout should be used in every page for the website. It includes the primary header and the footer of the website.
